Create Procedure sp_Promotion_Insert
--@Promotion_ID int IDENTITY(1,1) ,
@Promotion_NameVN nvarchar(50) ,
@Promotion_NameEN nvarchar(50) ,
@Promotion_UrlOut nvarchar(255) =NULL,
@Promotion_Rewrite nvarchar(255) ,
@Promotion_SearchVN varchar(50) =NULL,
@Promotion_SearchEN varchar(50) =NULL,
@Promotion_ContentVN nvarchar(max) =NULL,
@Promotion_ContentEN nvarchar(max) =NULL,
@Promotion_DescriptionVN nvarchar(max) =NULL,
@Promotion_DescriptionEN nvarchar(max) =NULL,
@Promotion_Img varchar(255) =NULL,
@Img_Width int =NULL,
@Img_Unit_Width varchar(10) =NULL,
@Img_Height int =NULL,
@Img_Unit_Height varchar(10) =NULL,
@Keyword_Titile nvarchar(50) =NULL,
@Keyword_Content nvarchar(max) =NULL,
@Keyword_Description nvarchar(max) =NULL,
@CreateDate datetime =NULL,
@CreateBy int =NULL,
@UpdateDate datetime =NULL,
@UpdateBy int =NULL,
@Lock int =NULL,
@Is_Active bit =NULL,
@Is_LeftPage bit =NULL,
@Is_RightPage bit =NULL,
@Display_Order int =NULL
As
Begin
	Insert into Promotion(
	Promotion_NameVN,
	Promotion_NameEN,
	Promotion_UrlOut,
	Promotion_Rewrite,
	Promotion_SearchVN,
	Promotion_SearchEN,
	Promotion_ContentVN,
	Promotion_ContentEN,
	Promotion_DescriptionVN,
	Promotion_DescriptionEN,
	Promotion_Img,
	Img_Width,
	Img_Unit_Width,
	Img_Height,
	Img_Unit_Height,
	Keyword_Titile,
	Keyword_Content,
	Keyword_Description,
	CreateDate,
	CreateBy,
	UpdateDate,
	UpdateBy,
	Lock,
	Is_Active,
	Is_LeftPage,
	Is_RightPage,
	Display_Order
	)
	Values
	(
	@Promotion_NameVN,
	@Promotion_NameEN,
	@Promotion_UrlOut ,
	@Promotion_Rewrite ,
	@Promotion_SearchVN ,
	@Promotion_SearchEN,
	@Promotion_ContentVN,
	@Promotion_ContentEN,
	@Promotion_DescriptionVN,
	@Promotion_DescriptionEN,
	@Promotion_Img,
	@Img_Width,
	@Img_Unit_Width,
	@Img_Height,
	@Img_Unit_Height,
	@Keyword_Titile,
	@Keyword_Content,
	@Keyword_Description,
	@CreateDate,
	@CreateBy,
	@UpdateDate,
	@UpdateBy,
	@Lock ,
	@Is_Active ,
	@Is_LeftPage,
	@Is_RightPage,
	@Display_Order
	)
End