Create Procedure sp_Promotion_Update
@Promotion_ID int,
@Promotion_NameVN nvarchar(50) ,
@Promotion_NameEN nvarchar(50) ,
@Promotion_UrlOut nvarchar(255) =NULL,
@Promotion_Rewrite nvarchar(255) ,
@Promotion_SearchVN varchar(50) =NULL,
@Promotion_SearchEN varchar(50) =NULL,
@Promotion_ContentVN nvarchar(max) =NULL,
@Promotion_ContentEN nvarchar(max) =NULL,
@Promotion_DescriptionVN nvarchar(max) =NULL,
@Promotion_DescriptionEN nvarchar(max) =NULL,
@Promotion_Img varchar(255) =NULL,
@Img_Width int =NULL,
@Img_Unit_Width varchar(10) =NULL,
@Img_Height int =NULL,
@Img_Unit_Height varchar(10) =NULL,
@Keyword_Titile nvarchar(50) =NULL,
@Keyword_Content nvarchar(max) =NULL,
@Keyword_Description nvarchar(max) =NULL,
@CreateDate datetime =NULL,
@CreateBy int =NULL,
@UpdateDate datetime =NULL,
@UpdateBy int =NULL,
@Lock int =NULL,
@Is_Active bit =NULL,
@Is_LeftPage bit =NULL,
@Is_RightPage bit =NULL,
@Display_Order int =NULL
As
Begin
	Update Pr
	Set Pr.Promotion_NameVN=@Promotion_NameVN,
      Pr.Promotion_NameEN=@Promotion_NameEN,
      Pr.Promotion_UrlOut=@Promotion_UrlOut ,
      Pr.Promotion_Rewrite=@Promotion_Rewrite ,
      Pr.Promotion_SearchVN=@Promotion_SearchVN ,
      Pr.Promotion_SearchEN=@Promotion_SearchEN,
      Pr.Promotion_ContentVN=@Promotion_ContentVN,
      Pr.Promotion_ContentEN=@Promotion_ContentEN,
      Pr.Promotion_DescriptionVN=@Promotion_DescriptionVN,
      Pr.Promotion_DescriptionEN=@Promotion_DescriptionEN,
      Pr.Promotion_Img=@Promotion_Img,
      Pr.Img_Width=@Img_Width,
      Pr.Img_Unit_Width=@Img_Unit_Width,
      Pr.Img_Height=@Img_Height,
      Pr.Img_Unit_Height=@Img_Unit_Height,
      Pr.Keyword_Titile=@Keyword_Titile,
      Pr.Keyword_Content=@Keyword_Content,
      Pr.Keyword_Description=@Keyword_Description,
      Pr.CreateDate=@CreateDate,
      Pr.CreateBy=@CreateBy,
      Pr.UpdateDate=@UpdateDate,
      Pr.UpdateBy=@UpdateBy,
      Pr.Lock=@Lock ,
      Pr.Is_Active=@Is_Active ,
      Pr.Is_LeftPage=@Is_LeftPage,
      Pr.Is_RightPage=@Is_RightPage,
      Pr.Display_Order=@Display_Order
	From Promotion Pr
	Where Pr.Promotion_ID=@Promotion_ID
End