Create Procedure sp_PageSetting_Insert
--@PageSetting_ID int,
@PageSetting_NameVN nvarchar(50) ,
@PageSetting_NameEN nvarchar(50) ,
@PageSetting_UrlOut nvarchar(255) = NULL,
@PageSetting_Rewrite nvarchar(255) ,
@PageSetting_SearchVN varchar(50) = NULL,
@PageSetting_SearchEN varchar(50) = NULL,
@PageSetting_Img varchar(255) = NULL,
@Img_Width int = NULL,
@Img_Unit_Width varchar(10) = NULL,
@Img_Height int = NULL,
@Img_Unit_Height varchar(10) = NULL,
@Keyword_Titile nvarchar(50) = NULL,
@Keyword_Content nvarchar(max) = NULL,
@Keyword_Description nvarchar(max) = NULL,
@CreateDate datetime = NULL,
@CreateBy int = NULL,
@UpdateDate datetime = NULL,
@UpdateBy int = NULL,
@Lock int = NULL,
@Is_Active bit = NULL,
@Is_TopPage bit = NULL,
@Is_LeftPage bit = NULL,
@Is_RightPage bit = NULL,
@Is_BottomPage bit = NULL,
@Display_Order int = NULL
As
Begin
	Insert into PageSetting(
	  PageSetting_NameVN,
      PageSetting_NameEN,
      PageSetting_UrlOut,
      PageSetting_Rewrite,
      PageSetting_SearchVN,
      PageSetting_SearchEN,
      PageSetting_Img,
      Img_Width,
      Img_Unit_Width,
      Img_Height,
      Img_Unit_Height,
      Keyword_Titile,
      Keyword_Content,
      Keyword_Description,
      CreateDate,
      CreateBy,
      UpdateDate,
      UpdateBy,
      Lock,
      Is_Active,
      Is_TopPage,
      Is_LeftPage,
      Is_RightPage,
      Is_BottomPage,
      Display_Order
	)
	Values
	(
	@PageSetting_NameVN,
	@PageSetting_NameEN,
	@PageSetting_UrlOut,
	@PageSetting_Rewrite,
	@PageSetting_SearchVN,
	@PageSetting_SearchEN,
	@PageSetting_Img,
	@Img_Width,
	@Img_Unit_Width,
	@Img_Height,
	@Img_Unit_Height,
	@Keyword_Titile,
	@Keyword_Content,
	@Keyword_Description,
	@CreateDate,
	@CreateBy,
	@UpdateDate,
	@UpdateBy,
	@Lock,
	@Is_Active,
	@Is_TopPage,
	@Is_LeftPage,
	@Is_RightPage,
	@Is_BottomPage,
	@Display_Order
	)
end