Create Procedure sp_PageSetting_Update
@PageSetting_ID int,
@PageSetting_NameVN nvarchar(50) ,
@PageSetting_NameEN nvarchar(50) ,
@PageSetting_UrlOut nvarchar(255) = NULL,
@PageSetting_Rewrite nvarchar(255) ,
@PageSetting_SearchVN varchar(50) = NULL,
@PageSetting_SearchEN varchar(50) = NULL,
@PageSetting_Img varchar(255) = NULL,
@Img_Width int = NULL,
@Img_Unit_Width varchar(10) = NULL,
@Img_Height int = NULL,
@Img_Unit_Height varchar(10) = NULL,
@Keyword_Titile nvarchar(50) = NULL,
@Keyword_Content nvarchar(max) = NULL,
@Keyword_Description nvarchar(max) = NULL,
@CreateDate datetime = NULL,
@CreateBy int = NULL,
@UpdateDate datetime = NULL,
@UpdateBy int = NULL,
@Lock int = NULL,
@Is_Active bit = NULL,
@Is_TopPage bit = NULL,
@Is_LeftPage bit = NULL,
@Is_RightPage bit = NULL,
@Is_BottomPage bit = NULL,
@Display_Order int = NULL
As
begin 
	Update Ps
	Set Ps.PageSetting_NameVN=@PageSetting_NameVN,
      Ps.PageSetting_NameEN=@PageSetting_NameEN,
      Ps.PageSetting_UrlOut=@PageSetting_UrlOut,
      Ps.PageSetting_Rewrite=@PageSetting_Rewrite,
      Ps.PageSetting_SearchVN=@PageSetting_SearchVN,
      Ps.PageSetting_SearchEN=@PageSetting_SearchEN,
      Ps.PageSetting_Img=@PageSetting_Img,
      Ps.Img_Width=@Img_Width,
      Ps.Img_Unit_Width=@Img_Unit_Width,
      Ps.Img_Height=@Img_Height,
      Ps.Img_Unit_Height=@Img_Unit_Height,
      Ps.Keyword_Titile=@Keyword_Titile,
      Ps.Keyword_Content=@Keyword_Content,
      Ps.Keyword_Description=@Keyword_Description,
      Ps.CreateDate=@CreateDate,
      Ps.CreateBy=@CreateBy,
      Ps.UpdateDate=@UpdateDate,
      Ps.UpdateBy=@UpdateBy,
      Ps.Lock=@Lock,
      Ps.Is_Active=@Is_Active,
      Ps.Is_TopPage=@Is_TopPage,
      Ps.Is_LeftPage=@Is_LeftPage,
      Ps.Is_RightPage=@Is_RightPage,
      Ps.Is_BottomPage=@Is_BottomPage,
      Ps.Display_Order=@Display_Order
	From PageSetting Ps
	Where Ps.PageSetting_ID=@PageSetting_ID

end