Create Procedure sp_Product_Insert
--@Product_ID int IDENTITY(1,1) ,
@Product_Code varchar(50) =NULL,
@Category_Parent_ID int ,
@Currency_ID int =NULL,
@Product_NameVN nvarchar(50) ,
@Product_NameEN nvarchar(50) ,
@Product_UrlOut nvarchar(255) =NULL,
@Product_Rewrite nvarchar(255) =NULL,
@Product_SearchVN varchar(50) ,
@Product_SearchEN varchar(50) ,
@Product_ContentVN nvarchar(max) =NULL,
@Product_ContentEN nvarchar(max) =NULL,
@Product_DescriptionVN nvarchar(max) =NULL,
@Product_DescriptionEN nvarchar(max) =NULL,
@Product_Price float =NULL,
@Product_Discount float =NULL,
@Product_Img varchar(255) =NULL,
@Img_Width int =NULL,
@Img_Unit_Width varchar(10) =NULL,
@Img_Height int =NULL,
@Img_Unit_Height varchar(10) =NULL,
@Keyword_Titile nvarchar(50) =NULL,
@Keyword_Content nvarchar(max) =NULL,
@Keyword_Description nvarchar(max) =NULL,
@CreateDate datetime =NULL,
@CreateBy int =NULL,
@UpdateDate datetime =NULL,
@UpdateBy int =NULL,
@Product_View int =NULL,
@Lock int =NULL,
@Is_Active bit =NULL,
@Is_HomePage bit =NULL,
@Is_TopMenu bit =NULL,
@Is_BottomMenu bit =NULL,
@Display_Order int =NULL
as
Begin
	Insert into Product(
	Product_Code,
	Category_Parent_ID,
	Currency_ID,
	Product_NameVN,
	Product_NameEN,
	Product_UrlOut,
	Product_Rewrite,
	Product_SearchVN,
	Product_SearchEN,
	Product_ContentVN,
	Product_ContentEN,
	Product_DescriptionVN,
	Product_DescriptionEN,
	Product_Price,
	Product_Discount,
	Product_Img,
	Img_Width,
	Img_Unit_Width,
	Img_Height,
	Img_Unit_Height,
	Keyword_Titile,
	Keyword_Content,
	Keyword_Description,
	CreateDate,
	CreateBy,
	UpdateDate,
	UpdateBy,
	Product_View,
	Lock,
	Is_Active,
	Is_HomePage,
	Is_TopMenu,
	Is_BottomMenu,
	Display_Order
	)
	Values
	(
	@Product_Code,
	@Category_Parent_ID,
	@Currency_ID,
	@Product_NameVN,
	@Product_NameEN,
	@Product_UrlOut,
	@Product_Rewrite,
	@Product_SearchVN,
	@Product_SearchEN,
	@Product_ContentVN,
	@Product_ContentEN,
	@Product_DescriptionVN,
	@Product_DescriptionEN,
	@Product_Price,
	@Product_Discount,
	@Product_Img,
	@Img_Width,
	@Img_Unit_Width,
	@Img_Height ,
	@Img_Unit_Height ,
	@Keyword_Titile ,
	@Keyword_Content ,
	@Keyword_Description,
	@CreateDate ,
	@CreateBy ,
	@UpdateDate,
	@UpdateBy ,
	@Product_View,
	@Lock ,
	@Is_Active ,
	@Is_HomePage,
	@Is_TopMenu ,
	@Is_BottomMenu ,
	@Display_Order
	)
End
