Create Procedure sp_Product_Update
@Product_ID int,
@Product_Code varchar(50) =NULL,
@Category_Parent_ID int ,
@Currency_ID int =NULL,
@Product_NameVN nvarchar(50) ,
@Product_NameEN nvarchar(50) ,
@Product_UrlOut nvarchar(255) =NULL,
@Product_Rewrite nvarchar(255) =NULL,
@Product_SearchVN varchar(50) ,
@Product_SearchEN varchar(50) ,
@Product_ContentVN nvarchar(max) =NULL,
@Product_ContentEN nvarchar(max) =NULL,
@Product_DescriptionVN nvarchar(max) =NULL,
@Product_DescriptionEN nvarchar(max) =NULL,
@Product_Price float =NULL,
@Product_Discount float =NULL,
@Product_Img varchar(255) =NULL,
@Img_Width int =NULL,
@Img_Unit_Width varchar(10) =NULL,
@Img_Height int =NULL,
@Img_Unit_Height varchar(10) =NULL,
@Keyword_Titile nvarchar(50) =NULL,
@Keyword_Content nvarchar(max) =NULL,
@Keyword_Description nvarchar(max) =NULL,
@CreateDate datetime =NULL,
@CreateBy int =NULL,
@UpdateDate datetime =NULL,
@UpdateBy int =NULL,
@Product_View int =NULL,
@Lock int =NULL,
@Is_Active bit =NULL,
@Is_HomePage bit =NULL,
@Is_TopMenu bit =NULL,
@Is_BottomMenu bit =NULL,
@Display_Order int =NULL
as
Begin
	Update P
	Set P.Product_Code=@Product_Code,
      P.Category_Parent_ID=@Category_Parent_ID,
      P.Currency_ID=@Currency_ID,
      P.Product_NameVN=@Product_NameVN,
      P.Product_NameEN=@Product_NameEN,
      P.Product_UrlOut=@Product_UrlOut,
      P.Product_Rewrite=@Product_Rewrite,
      P.Product_SearchVN=@Product_SearchVN,
      P.Product_SearchEN=@Product_SearchEN,
      P.Product_ContentVN=@Product_ContentVN,
      P.Product_ContentEN=@Product_ContentEN,
      P.Product_DescriptionVN=@Product_DescriptionVN,
      P.Product_DescriptionEN=@Product_DescriptionEN,
      P.Product_Price=@Product_Price,
      P.Product_Discount=@Product_Discount,
      P.Product_Img=@Product_Img,
      P.Img_Width=@Img_Width,
      P.Img_Unit_Width=@Img_Unit_Width,
      P.Img_Height=@Img_Height ,
      P.Img_Unit_Height=@Img_Unit_Height ,
      P.Keyword_Titile=@Keyword_Titile ,
      P.Keyword_Content=@Keyword_Content ,
      P.Keyword_Description=@Keyword_Description,
      P.CreateDate=@CreateDate ,
      P.CreateBy=@CreateBy ,
      P.UpdateDate=@UpdateDate,
      P.UpdateBy=@UpdateBy ,
      P.Product_View=@Product_View,
      P.Lock=@Lock ,
      P.Is_Active=@Is_Active ,
      P.Is_HomePage=@Is_HomePage,
      P.Is_TopMenu=@Is_TopMenu ,
      P.Is_BottomMenu=@Is_BottomMenu ,
      P.Display_Order=@Display_Order
	From Product P
	Where P.Product_ID=@Product_ID
End