// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DbContextPOCO.Entity
{

    // Advertisement
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class AdvertisementConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Advertisement>
    {
        public AdvertisementConfiguration()
            : this("dbo")
        {
        }

        public AdvertisementConfiguration(string schema)
        {
            ToTable("Advertisement", schema);
            HasKey(x => x.AdvertisementId);

            Property(x => x.AdvertisementId).HasColumnName(@"Advertisement_ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.AdvertisementNameVn).HasColumnName(@"Advertisement_NameVN").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.AdvertisementNameEn).HasColumnName(@"Advertisement_NameEN").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.AdvertisementUrlOut).HasColumnName(@"Advertisement_UrlOut").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.AdvertisementRewrite).HasColumnName(@"Advertisement_Rewrite").HasColumnType("nvarchar").IsRequired().HasMaxLength(255);
            Property(x => x.AdvertisementSearchVn).HasColumnName(@"Advertisement_SearchVN").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.AdvertisementSearchEn).HasColumnName(@"Advertisement_SearchEN").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.AdvertisementContentVn).HasColumnName(@"Advertisement_ContentVN").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.AdvertisementContentEn).HasColumnName(@"Advertisement_ContentEN").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.AdvertisementDescriptionVn).HasColumnName(@"Advertisement_DescriptionVN").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.AdvertisementDescriptionEn).HasColumnName(@"Advertisement_DescriptionEN").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.AdvertisementImg).HasColumnName(@"Advertisement_Img").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.ImgWidth).HasColumnName(@"Img_Width").HasColumnType("int").IsOptional();
            Property(x => x.ImgUnitWidth).HasColumnName(@"Img_Unit_Width").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(10);
            Property(x => x.ImgHeight).HasColumnName(@"Img_Height").HasColumnType("int").IsOptional();
            Property(x => x.ImgUnitHeight).HasColumnName(@"Img_Unit_Height").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(10);
            Property(x => x.KeywordTitile).HasColumnName(@"Keyword_Titile").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.KeywordContent).HasColumnName(@"Keyword_Content").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.KeywordDescription).HasColumnName(@"Keyword_Description").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.CreateDate).HasColumnName(@"CreateDate").HasColumnType("datetime").IsOptional();
            Property(x => x.CreateBy).HasColumnName(@"CreateBy").HasColumnType("int").IsOptional();
            Property(x => x.UpdateDate).HasColumnName(@"UpdateDate").HasColumnType("datetime").IsOptional();
            Property(x => x.UpdateBy).HasColumnName(@"UpdateBy").HasColumnType("int").IsOptional();
            Property(x => x.Lock).HasColumnName(@"Lock").HasColumnType("int").IsOptional();
            Property(x => x.IsActive).HasColumnName(@"Is_Active").HasColumnType("bit").IsOptional();
            Property(x => x.IsTopPage).HasColumnName(@"Is_TopPage").HasColumnType("bit").IsOptional();
            Property(x => x.IsLeftPage).HasColumnName(@"Is_LeftPage").HasColumnType("bit").IsOptional();
            Property(x => x.IsRightPage).HasColumnName(@"Is_RightPage").HasColumnType("bit").IsOptional();
            Property(x => x.IsBottomPage).HasColumnName(@"Is_BottomPage").HasColumnType("bit").IsOptional();
            Property(x => x.DisplayOrder).HasColumnName(@"Display_Order").HasColumnType("int").IsOptional();
        }
    }

}
// </auto-generated>
