// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DbContextPOCO.Entity
{

    // Contact
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class Contact
    {
        public int ContactId { get; set; } // Contact_ID (Primary key)
        public string ContactName { get; set; } // Contact_Name (length: 50)
        public string ContactCellPhone { get; set; } // Contact_CellPhone (length: 50)
        public string ContactEmail { get; set; } // Contact_Email (length: 50)
        public string ContactAddress { get; set; } // Contact_Address
        public System.DateTime ContactDate { get; set; } // Contact_Date
        public bool? IsActive { get; set; } // Is_Active

        public Contact()
        {
            ContactDate = System.DateTime.Now;
            IsActive = true;
        }
    }

}
// </auto-generated>
