// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DbContextPOCO.Entity
{

    // Contact
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class ContactConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Contact>
    {
        public ContactConfiguration()
            : this("dbo")
        {
        }

        public ContactConfiguration(string schema)
        {
            ToTable("Contact", schema);
            HasKey(x => x.ContactId);

            Property(x => x.ContactId).HasColumnName(@"Contact_ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ContactName).HasColumnName(@"Contact_Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.ContactCellPhone).HasColumnName(@"Contact_CellPhone").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ContactEmail).HasColumnName(@"Contact_Email").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ContactAddress).HasColumnName(@"Contact_Address").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.ContactDate).HasColumnName(@"Contact_Date").HasColumnType("datetime").IsRequired();
            Property(x => x.IsActive).HasColumnName(@"Is_Active").HasColumnType("bit").IsOptional();
        }
    }

}
// </auto-generated>
