// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DbContextPOCO.Entity
{

    // OrderMaster
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class OrderMasterConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<OrderMaster>
    {
        public OrderMasterConfiguration()
            : this("dbo")
        {
        }

        public OrderMasterConfiguration(string schema)
        {
            ToTable("OrderMaster", schema);
            HasKey(x => x.OrderMasterId);

            Property(x => x.OrderMasterId).HasColumnName(@"OrderMaster_ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UserProfileId).HasColumnName(@"UserProfile_ID").HasColumnType("int").IsRequired();
            Property(x => x.PaymentId).HasColumnName(@"Payment_ID").HasColumnType("int").IsOptional();
            Property(x => x.ProviceId).HasColumnName(@"Provice_ID").HasColumnType("int").IsOptional();
            Property(x => x.OrderMasterCode).HasColumnName(@"OrderMaster_Code").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.PriceShip).HasColumnName(@"PriceShip").HasColumnType("float").IsOptional();
            Property(x => x.Vat).HasColumnName(@"VAT").HasColumnType("float").IsOptional();
            Property(x => x.Total).HasColumnName(@"Total").HasColumnType("float").IsOptional();
            Property(x => x.Note).HasColumnName(@"Note").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.OrderMasterDate).HasColumnName(@"OrderMaster_Date").HasColumnType("datetime").IsRequired();
            Property(x => x.OrderMasterStatus).HasColumnName(@"OrderMaster_Status").HasColumnType("int").IsOptional();
            Property(x => x.Lock).HasColumnName(@"Lock").HasColumnType("int").IsOptional();
            Property(x => x.IsActive).HasColumnName(@"Is_Active").HasColumnType("bit").IsOptional();

            // Foreign keys
            HasRequired(a => a.UserProfile).WithMany(b => b.OrderMasters).HasForeignKey(c => c.UserProfileId).WillCascadeOnDelete(false); // FK_OrderMaster_UserProfile
        }
    }

}
// </auto-generated>
