// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DbContextPOCO.Entity
{

    // Promotion
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class PromotionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Promotion>
    {
        public PromotionConfiguration()
            : this("dbo")
        {
        }

        public PromotionConfiguration(string schema)
        {
            ToTable("Promotion", schema);
            HasKey(x => x.PromotionId);

            Property(x => x.PromotionId).HasColumnName(@"Promotion_ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PromotionNameVn).HasColumnName(@"Promotion_NameVN").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.PromotionNameEn).HasColumnName(@"Promotion_NameEN").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.PromotionUrlOut).HasColumnName(@"Promotion_UrlOut").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.PromotionRewrite).HasColumnName(@"Promotion_Rewrite").HasColumnType("nvarchar").IsRequired().HasMaxLength(255);
            Property(x => x.PromotionSearchVn).HasColumnName(@"Promotion_SearchVN").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.PromotionSearchEn).HasColumnName(@"Promotion_SearchEN").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.PromotionContentVn).HasColumnName(@"Promotion_ContentVN").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.PromotionContentEn).HasColumnName(@"Promotion_ContentEN").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.PromotionDescriptionVn).HasColumnName(@"Promotion_DescriptionVN").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.PromotionDescriptionEn).HasColumnName(@"Promotion_DescriptionEN").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.PromotionImg).HasColumnName(@"Promotion_Img").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.ImgWidth).HasColumnName(@"Img_Width").HasColumnType("int").IsOptional();
            Property(x => x.ImgUnitWidth).HasColumnName(@"Img_Unit_Width").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(10);
            Property(x => x.ImgHeight).HasColumnName(@"Img_Height").HasColumnType("int").IsOptional();
            Property(x => x.ImgUnitHeight).HasColumnName(@"Img_Unit_Height").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(10);
            Property(x => x.KeywordTitile).HasColumnName(@"Keyword_Titile").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.KeywordContent).HasColumnName(@"Keyword_Content").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.KeywordDescription).HasColumnName(@"Keyword_Description").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.CreateDate).HasColumnName(@"CreateDate").HasColumnType("datetime").IsOptional();
            Property(x => x.CreateBy).HasColumnName(@"CreateBy").HasColumnType("int").IsOptional();
            Property(x => x.UpdateDate).HasColumnName(@"UpdateDate").HasColumnType("datetime").IsOptional();
            Property(x => x.UpdateBy).HasColumnName(@"UpdateBy").HasColumnType("int").IsOptional();
            Property(x => x.Lock).HasColumnName(@"Lock").HasColumnType("int").IsOptional();
            Property(x => x.IsActive).HasColumnName(@"Is_Active").HasColumnType("bit").IsOptional();
            Property(x => x.IsLeftPage).HasColumnName(@"Is_LeftPage").HasColumnType("bit").IsOptional();
            Property(x => x.IsRightPage).HasColumnName(@"Is_RightPage").HasColumnType("bit").IsOptional();
            Property(x => x.DisplayOrder).HasColumnName(@"Display_Order").HasColumnType("int").IsOptional();
        }
    }

}
// </auto-generated>
