// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DbContextPOCO.Entity
{

    // Roles
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class Role
    {
        public int RolesId { get; set; } // Roles_ID (Primary key)
        public string RolesName { get; set; } // Roles_Name (length: 20)
        public bool? IsActive { get; set; } // Is_Active
        public int? DisplayOrder { get; set; } // Display_Order

        // Reverse navigation

        /// <summary>
        /// Child UserRoles where [UserRoles].[Roles_ID] point to this entity (FK_UserRoles_Roles)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<UserRole> UserRoles { get; set; } // UserRoles.FK_UserRoles_Roles

        public Role()
        {
            IsActive = false;
            DisplayOrder = 1;
        }
    }

}
// </auto-generated>
