// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DbContextPOCO.Entity
{

    // SysFunctionInGroup
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SysFunctionInGroupConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SysFunctionInGroup>
    {
        public SysFunctionInGroupConfiguration()
            : this("dbo")
        {
        }

        public SysFunctionInGroupConfiguration(string schema)
        {
            ToTable("SysFunctionInGroup", schema);
            HasKey(x => x.SysFunctionInGroupId);

            Property(x => x.SysFunctionInGroupId).HasColumnName(@"SysFunctionInGroupId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.GroupRolesId).HasColumnName(@"GroupRolesId").HasColumnType("int").IsOptional();
            Property(x => x.FuctionId).HasColumnName(@"FuctionId").HasColumnType("int").IsOptional();
            Property(x => x.Descriptions).HasColumnName(@"Descriptions").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.DisplayOrder).HasColumnName(@"Display_Order").HasColumnType("int").IsOptional();
            Property(x => x.IsActive).HasColumnName(@"Is_Active").HasColumnType("bit").IsOptional();
            Property(x => x.CreateDate).HasColumnName(@"CreateDate").HasColumnType("datetime").IsOptional();
            Property(x => x.CreateBy).HasColumnName(@"CreateBy").HasColumnType("int").IsOptional();
            Property(x => x.UpdateDate).HasColumnName(@"UpdateDate").HasColumnType("datetime").IsOptional();
            Property(x => x.UpdateBy).HasColumnName(@"UpdateBy").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.SysFunction).WithMany(b => b.SysFunctionInGroups).HasForeignKey(c => c.FuctionId).WillCascadeOnDelete(false); // FK_SysFunctionInGroup_SysFunction
            HasOptional(a => a.SysGroupRole).WithMany(b => b.SysFunctionInGroups).HasForeignKey(c => c.GroupRolesId).WillCascadeOnDelete(false); // FK_SysFunctionInGroup_SysGroupRoles
        }
    }

}
// </auto-generated>
