// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DbContextPOCO.Entity
{

    // SysFunctionGroup
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SysFunctionGroupConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SysFunctionGroup>
    {
        public SysFunctionGroupConfiguration()
            : this("dbo")
        {
        }

        public SysFunctionGroupConfiguration(string schema)
        {
            ToTable("SysFunctionGroup", schema);
            HasKey(x => x.SysFunctionGroupId);

            Property(x => x.SysFunctionGroupId).HasColumnName(@"SysFunctionGroupId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.SysFunctionGroupCode).HasColumnName(@"SysFunctionGroupCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.SysFunctionGroupName).HasColumnName(@"SysFunctionGroupName").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.Descriptions).HasColumnName(@"Descriptions").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.DisplayOrder).HasColumnName(@"Display_Order").HasColumnType("int").IsOptional();
            Property(x => x.IsActive).HasColumnName(@"Is_Active").HasColumnType("bit").IsOptional();
            Property(x => x.CreateDate).HasColumnName(@"CreateDate").HasColumnType("datetime").IsOptional();
            Property(x => x.CreateBy).HasColumnName(@"CreateBy").HasColumnType("int").IsOptional();
            Property(x => x.UpdateDate).HasColumnName(@"UpdateDate").HasColumnType("datetime").IsOptional();
            Property(x => x.UpdateBy).HasColumnName(@"UpdateBy").HasColumnType("int").IsOptional();
        }
    }

}
// </auto-generated>
