// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DbContextPOCO.Entity
{

    // SysFunction
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SysFunctionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SysFunction>
    {
        public SysFunctionConfiguration()
            : this("dbo")
        {
        }

        public SysFunctionConfiguration(string schema)
        {
            ToTable("SysFunction", schema);
            HasKey(x => x.FunctionId);

            Property(x => x.FunctionId).HasColumnName(@"FunctionId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.TreePanelId).HasColumnName(@"TreePanelId").HasColumnType("int").IsOptional();
            Property(x => x.SysFunctionGroupId).HasColumnName(@"SysFunctionGroupId").HasColumnType("int").IsOptional();
            Property(x => x.FunctionCode).HasColumnName(@"FunctionCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.FunctionName).HasColumnName(@"FunctionName").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.ButtonId).HasColumnName(@"ButtonId").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.DisplayOrder).HasColumnName(@"Display_Order").HasColumnType("int").IsOptional();
            Property(x => x.IsActive).HasColumnName(@"Is_Active").HasColumnType("bit").IsOptional();
            Property(x => x.CreateDate).HasColumnName(@"CreateDate").HasColumnType("datetime").IsOptional();
            Property(x => x.CreateBy).HasColumnName(@"CreateBy").HasColumnType("int").IsOptional();
            Property(x => x.UpateDate).HasColumnName(@"UpateDate").HasColumnType("datetime").IsOptional();
            Property(x => x.UpdateBy).HasColumnName(@"UpdateBy").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.SysFunctionGroup).WithMany(b => b.SysFunctions).HasForeignKey(c => c.SysFunctionGroupId).WillCascadeOnDelete(false); // FK_SysFunction_SysFunctionGroup
        }
    }

}
// </auto-generated>
