// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DbContextPOCO.Entity
{

    // SysFunctionGroup
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SysFunctionGroup
    {
        public int SysFunctionGroupId { get; set; } // SysFunctionGroupId (Primary key)
        public string SysFunctionGroupCode { get; set; } // SysFunctionGroupCode (length: 50)
        public string SysFunctionGroupName { get; set; } // SysFunctionGroupName (length: 255)
        public string Descriptions { get; set; } // Descriptions
        public int? DisplayOrder { get; set; } // Display_Order
        public bool? IsActive { get; set; } // Is_Active
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public int? CreateBy { get; set; } // CreateBy
        public System.DateTime? UpdateDate { get; set; } // UpdateDate
        public int? UpdateBy { get; set; } // UpdateBy

        // Reverse navigation

        /// <summary>
        /// Child SysFunctions where [SysFunction].[SysFunctionGroupId] point to this entity (FK_SysFunction_SysFunctionGroup)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SysFunction> SysFunctions { get; set; } // SysFunction.FK_SysFunction_SysFunctionGroup

        public SysFunctionGroup()
        {
            SysFunctions = new System.Collections.Generic.List<SysFunction>();
        }
    }

}
// </auto-generated>
