// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DbContextPOCO.Entity
{

    // SysFunctionInGroup
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SysFunctionInGroup
    {
        public int SysFunctionInGroupId { get; set; } // SysFunctionInGroupId (Primary key)
        public int? GroupRolesId { get; set; } // GroupRolesId
        public int? FuctionId { get; set; } // FuctionId
        public string Descriptions { get; set; } // Descriptions
        public int? DisplayOrder { get; set; } // Display_Order
        public bool? IsActive { get; set; } // Is_Active
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public int? CreateBy { get; set; } // CreateBy
        public System.DateTime? UpdateDate { get; set; } // UpdateDate
        public int? UpdateBy { get; set; } // UpdateBy

        // Foreign keys

        /// <summary>
        /// Parent SysFunction pointed by [SysFunctionInGroup].([FuctionId]) (FK_SysFunctionInGroup_SysFunction)
        /// </summary>
        public virtual SysFunction SysFunction { get; set; } // FK_SysFunctionInGroup_SysFunction

        /// <summary>
        /// Parent SysGroupRole pointed by [SysFunctionInGroup].([GroupRolesId]) (FK_SysFunctionInGroup_SysGroupRoles)
        /// </summary>
        public virtual SysGroupRole SysGroupRole { get; set; } // FK_SysFunctionInGroup_SysGroupRoles
    }

}
// </auto-generated>
