// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DbContextPOCO.Entity
{

    // SysGroupRoles
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SysGroupRole
    {
        public int GroupRolesId { get; set; } // GroupRolesId (Primary key)
        public string GroupRolesCode { get; set; } // GroupRolesCode (length: 50)
        public string GroupRolesName { get; set; } // GroupRolesName (length: 50)
        public bool? IsActive { get; set; } // Is_Active
        public int? DisplayOrder { get; set; } // Display_Order
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public int? CreateBy { get; set; } // CreateBy
        public System.DateTime? UpdateDate { get; set; } // UpdateDate
        public int? UpdateBy { get; set; } // UpdateBy

        // Reverse navigation

        /// <summary>
        /// Child SysFunctionInGroups where [SysFunctionInGroup].[GroupRolesId] point to this entity (FK_SysFunctionInGroup_SysGroupRoles)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SysFunctionInGroup> SysFunctionInGroups { get; set; } // SysFunctionInGroup.FK_SysFunctionInGroup_SysGroupRoles
        /// <summary>
        /// Child SysUserInGroups where [SysUserInGroup].[GroupRolesId] point to this entity (FK_SysUserInGroup_SysGroupRoles)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SysUserInGroup> SysUserInGroups { get; set; } // SysUserInGroup.FK_SysUserInGroup_SysGroupRoles

        public SysGroupRole()
        {
            IsActive = false;
            DisplayOrder = 1;
            SysFunctionInGroups = new System.Collections.Generic.List<SysFunctionInGroup>();
            SysUserInGroups = new System.Collections.Generic.List<SysUserInGroup>();
        }
    }

}
// </auto-generated>
