// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DbContextPOCO.Entity
{

    // SysUserInGroup
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SysUserInGroupConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SysUserInGroup>
    {
        public SysUserInGroupConfiguration()
            : this("dbo")
        {
        }

        public SysUserInGroupConfiguration(string schema)
        {
            ToTable("SysUserInGroup", schema);
            HasKey(x => x.SysUserInGroupId);

            Property(x => x.SysUserInGroupId).HasColumnName(@"SysUserInGroupId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.GroupRolesId).HasColumnName(@"GroupRolesId").HasColumnType("int").IsOptional();
            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("int").IsOptional();
            Property(x => x.Descriptions).HasColumnName(@"Descriptions").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.DisplayOrder).HasColumnName(@"Display_Order").HasColumnType("int").IsOptional();
            Property(x => x.IsActive).HasColumnName(@"Is_Active").HasColumnType("bit").IsOptional();
            Property(x => x.CreateDate).HasColumnName(@"CreateDate").HasColumnType("datetime").IsOptional();
            Property(x => x.CreateBy).HasColumnName(@"CreateBy").HasColumnType("int").IsOptional();
            Property(x => x.UpdateDate).HasColumnName(@"UpdateDate").HasColumnType("datetime").IsOptional();
            Property(x => x.UpdateBy).HasColumnName(@"UpdateBy").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.SysGroupRole).WithMany(b => b.SysUserInGroups).HasForeignKey(c => c.GroupRolesId).WillCascadeOnDelete(false); // FK_SysUserInGroup_SysGroupRoles
            HasOptional(a => a.UserProfile).WithMany(b => b.SysUserInGroups).HasForeignKey(c => c.UserId).WillCascadeOnDelete(false); // FK_SysUserInGroup_UserProfile
        }
    }

}
// </auto-generated>
