// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DbContextPOCO.Entity
{

    // SysUserInGroup
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SysUserInGroup
    {
        public int SysUserInGroupId { get; set; } // SysUserInGroupId (Primary key)
        public int? GroupRolesId { get; set; } // GroupRolesId
        public int? UserId { get; set; } // UserId
        public string Descriptions { get; set; } // Descriptions
        public int? DisplayOrder { get; set; } // Display_Order
        public bool? IsActive { get; set; } // Is_Active
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public int? CreateBy { get; set; } // CreateBy
        public System.DateTime? UpdateDate { get; set; } // UpdateDate
        public int? UpdateBy { get; set; } // UpdateBy

        // Foreign keys

        /// <summary>
        /// Parent SysGroupRole pointed by [SysUserInGroup].([GroupRolesId]) (FK_SysUserInGroup_SysGroupRoles)
        /// </summary>
        public virtual SysGroupRole SysGroupRole { get; set; } // FK_SysUserInGroup_SysGroupRoles

        /// <summary>
        /// Parent UserProfile pointed by [SysUserInGroup].([UserId]) (FK_SysUserInGroup_UserProfile)
        /// </summary>
        public virtual UserProfile UserProfile { get; set; } // FK_SysUserInGroup_UserProfile
    }

}
// </auto-generated>
