// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DbContextPOCO.Entity
{

    // UserRoles
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class UserRole
    {
        public int UserRolesId { get; set; } // UserRoles_ID (Primary key)
        public int? RolesId { get; set; } // Roles_ID
        public int? UserProfileId { get; set; } // UserProfile_ID
        public bool? IsActive { get; set; } // Is_Active
        public int? DisplayOrder { get; set; } // Display_Order

        // Foreign keys

        /// <summary>
        /// Parent Role pointed by [UserRoles].([RolesId]) (FK_UserRoles_Roles)
        /// </summary>
        public virtual Role Role { get; set; } // FK_UserRoles_Roles

        /// <summary>
        /// Parent UserProfile pointed by [UserRoles].([UserProfileId]) (FK_UserRoles_UserProfile)
        /// </summary>
        public virtual UserProfile UserProfile { get; set; } // FK_UserRoles_UserProfile

        public UserRole()
        {
            IsActive = false;
            DisplayOrder = 1;
        }
    }

}
// </auto-generated>
