// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DbContextPOCO.Entity
{

    // UserRoles
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class UserRoleConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UserRole>
    {
        public UserRoleConfiguration()
            : this("dbo")
        {
        }

        public UserRoleConfiguration(string schema)
        {
            ToTable("UserRoles", schema);
            HasKey(x => x.UserRolesId);

            Property(x => x.UserRolesId).HasColumnName(@"UserRoles_ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.RolesId).HasColumnName(@"Roles_ID").HasColumnType("int").IsOptional();
            Property(x => x.UserProfileId).HasColumnName(@"UserProfile_ID").HasColumnType("int").IsOptional();
            Property(x => x.IsActive).HasColumnName(@"Is_Active").HasColumnType("bit").IsOptional();
            Property(x => x.DisplayOrder).HasColumnName(@"Display_Order").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.Role).WithMany(b => b.UserRoles).HasForeignKey(c => c.RolesId).WillCascadeOnDelete(false); // FK_UserRoles_Roles
            HasOptional(a => a.UserProfile).WithMany(b => b.UserRoles).HasForeignKey(c => c.UserProfileId).WillCascadeOnDelete(false); // FK_UserRoles_UserProfile
        }
    }

}
// </auto-generated>
