// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DbContextPOCO.Entity
{

    // UserProfile
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class UserProfile
    {
        public int UserProfileId { get; set; } // UserProfile_ID (Primary key)
        public string UserProfileLastName { get; set; } // UserProfile_LastName (length: 50)
        public string UserProfileFirstName { get; set; } // UserProfile_FirstName (length: 50)
        public string UserProfileFullName { get; set; } // UserProfile_FullName (length: 255)
        public int UserProfileBirthDay { get; set; } // UserProfile_Birth_Day
        public int UserProfileBirthMonth { get; set; } // UserProfile_Birth_Month
        public int UserProfileBirthYear { get; set; } // UserProfile_Birth_Year
        public int? UserProfileAge { get; set; } // UserProfile_Age
        public string UserProfileGender { get; set; } // UserProfile_Gender (length: 10)
        public string UserProfilePhone { get; set; } // UserProfile_Phone (length: 20)
        public string UserProfileEmail { get; set; } // UserProfile_Email (length: 50)
        public string UserProfilePass { get; set; } // UserProfile_Pass (length: 50)
        public string UserProfileAboutMe { get; set; } // UserProfile_About_Me
        public string UserProfileAvatar { get; set; } // UserProfile_Avatar (length: 500)
        public string UserProfileConnectId { get; set; } // UserProfile_ConnectID
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public System.DateTime? UpdateDate { get; set; } // UpdateDate
        public int? Lock { get; set; } // Lock
        public bool? IsActive { get; set; } // Is_Active

        // Reverse navigation

        /// <summary>
        /// Child OrderMasters where [OrderMaster].[UserProfile_ID] point to this entity (FK_OrderMaster_UserProfile)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<OrderMaster> OrderMasters { get; set; } // OrderMaster.FK_OrderMaster_UserProfile
        /// <summary>
        /// Child UserRoles where [UserRoles].[UserProfile_ID] point to this entity (FK_UserRoles_UserProfile)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<UserRole> UserRoles { get; set; } // UserRoles.FK_UserRoles_UserProfile

        public UserProfile()
        {
            CreateDate = System.DateTime.Now;
            UpdateDate = System.DateTime.Now;
            Lock = 0;
            IsActive = true;
            OrderMasters = new System.Collections.Generic.List<OrderMaster>();
            UserRoles = new System.Collections.Generic.List<UserRole>();
        }
    }

}
// </auto-generated>
