Create Procedure sp_Advertisement_Insert
	--@Advertisement_ID int IDENTITY(1,1) ,
	@Advertisement_NameVN nvarchar(50) ,
	@Advertisement_NameEN nvarchar(50) ,
	@Advertisement_UrlOut nvarchar(255) =NULL,
	@Advertisement_Rewrite nvarchar(255) ,
	@Advertisement_SearchVN varchar(50) =NULL,
	@Advertisement_SearchEN varchar(50) =NULL,
	@Advertisement_ContentVN nvarchar(max) =NULL,
	@Advertisement_ContentEN nvarchar(max) =NULL,
	@Advertisement_DescriptionVN nvarchar(max) =NULL,
	@Advertisement_DescriptionEN nvarchar(max) =NULL,
	@Advertisement_Img varchar(255) =NULL,
	@Img_Width int =NULL,
	@Img_Unit_Width varchar(10) =NULL,
	@Img_Height int =NULL,
	@Img_Unit_Height varchar(10) =NULL,
	@Keyword_Titile nvarchar(50) =NULL,
	@Keyword_Content nvarchar(max) =NULL,
	@Keyword_Description nvarchar(max) =NULL,
	@CreateDate datetime =NULL,
	@CreateBy int =NULL,
	@UpdateDate datetime =NULL,
	@UpdateBy int =NULL,
	@Lock int =NULL,
	@Is_Active bit= NULL,
	@Is_TopPage bit= NULL,
	@Is_LeftPage bit= NULL,
	@Is_RightPage bit= NULL,
	@Is_BottomPage bit= NULL,
	@Display_Order int =NULL
as
Begin
	Insert into Advertisement (
	  Advertisement_NameVN,
      Advertisement_NameEN,
      Advertisement_UrlOut,
      Advertisement_Rewrite,
      Advertisement_SearchVN,
      Advertisement_SearchEN,
      Advertisement_ContentVN,
      Advertisement_ContentEN,
      Advertisement_DescriptionVN,
      Advertisement_DescriptionEN,
      Advertisement_Img,
      Img_Width,
      Img_Unit_Width,
      Img_Height,
      Img_Unit_Height,
      Keyword_Titile,
      Keyword_Content,
      Keyword_Description,
      CreateDate,
      CreateBy,
      UpdateDate,
      UpdateBy,
      Lock,
      Is_Active,
      Is_TopPage,
      Is_LeftPage,
      Is_RightPage,
      Is_BottomPage,
      Display_Order
	)
	Values (
	@Advertisement_NameVN,
	@Advertisement_NameEN,
	@Advertisement_UrlOut,
	@Advertisement_Rewrite,
	@Advertisement_SearchVN,
	@Advertisement_SearchEN,
	@Advertisement_ContentVN,
	@Advertisement_ContentEN,
	@Advertisement_DescriptionVN,
	@Advertisement_DescriptionEN,
	@Advertisement_Img,
	@Img_Width,
	@Img_Unit_Width,
	@Img_Height,
	@Img_Unit_Height,
	@Keyword_Titile,
	@Keyword_Content,
	@Keyword_Description,
	@CreateDate,
	@CreateBy,
	@UpdateDate,
	@UpdateBy,
	@Lock ,
	@Is_Active ,
	@Is_TopPage ,
	@Is_LeftPage ,
	@Is_RightPage ,
	@Is_BottomPage ,
	@Display_Order
	)
End