Create Proc sp_Category_Update
	@Category_ID int,
	@Category_Parent_ID int ,
	@Category_NameVN nvarchar(50) ,
	@Category_NameEN nvarchar(50) ,
	@Category_UrlOut nvarchar(255) =NULL,
	@Category_Rewrite nvarchar(255) ,
	@Category_SearchVN varchar(50) =NULL,
	@Category_SearchEN varchar(50) =NULL,
	@Category_Icon varchar(255) =NULL,
	@Category_Img varchar(255) =NULL,
	@Keyword_Titile nvarchar(50) =NULL,
	@Keyword_Content nvarchar(max) =NULL,
	@Keyword_Description nvarchar(max) =NULL,
	@CreateDate datetime =NULL,
	@CreateBy int =NULL,
	@UpdateDate datetime =NULL,
	@UpdateBy int =NULL,
	@Lock int =NULL,
	@Is_Active bit =NULL,
	@Is_HomePage bit =NULL,
	@Is_TopMenu bit =NULL,
	@Is_BottomMenu bit =NULL,
	@Display_Order int =NULL
AS
BEGIN 
	UPDATE C SET C.Category_Parent_ID=@Category_Parent_ID,
      C.Category_NameVN=@Category_NameVN,
      C.Category_NameEN=@Category_NameEN,
      C.Category_UrlOut=@Category_UrlOut,
      C.Category_Rewrite=@Category_Rewrite,
      C.Category_SearchVN=@Category_SearchVN,
      C.Category_SearchEN=@Category_SearchEN,
      C.Category_Icon=@Category_Icon,
      C.Category_Img=@Category_Img,
      C.Keyword_Titile=@Keyword_Titile,
      C.Keyword_Content=@Keyword_Content,
      C.Keyword_Description=@Keyword_Description,
      C.CreateDate=@CreateDate,
      C.CreateBy=@CreateBy,
      C.UpdateDate=@UpdateDate,
      C.UpdateBy=@UpdateBy,
      C.Lock=@Lock,
      C.Is_Active=@Is_Active,
      C.Is_HomePage=@Is_HomePage,
      C.Is_TopMenu=@Is_TopMenu,
      C.Is_BottomMenu=@Is_BottomMenu,
      C.Display_Order=@Display_Order
	FROM Category C
	WHERE C.Category_ID=@Category_ID
END
